### ISSUE TITLE
Provide csv sample data

### ISSUE THREAD

**Issue by giuliomarin** [l0drex/family-tree#22]
I'm trying out this project and I'd love to have some sample csv files. I tried to use the examples in the readme but I get some errors like `Assertion Failed: Some people have no generation defined`. Is it possible to include one example in the repo that people can just download and upload here? https://l0drex.github.io./family-tree

**Comment by l0drex** [comment]
Oh, must have missed that. "Grandgrandmother" and "someone" are actually not connected to the rest of the family in the data. Must have added those for testing at some point, I will fix that.
